package dev.haomin.resumer.app.common.id

import com.fasterxml.uuid.Generators
import java.util.UUID

/**
 * A functional interface representing a generator that produces sequential or unique identifiers of type [T].
 *
 * @param T The type of the identifiers generated by this interface.
 */
fun interface IdGenerator<T> {
    fun next(): T
}

/**
 * A singleton object that generates unique identifiers of type [UUID] based on a time-based epoch random generator.
 *
 * Implements the [IdGenerator] interface specialized for [UUID].
 *
 * This generator is thread-safe and designed to produce identifiers suitable for cases
 * where uniqueness is required, such as database keys or distributed systems.
 */
object UUIDGenerator: IdGenerator<UUID> {
    private val generator = Generators.timeBasedEpochRandomGenerator()

    override fun next(): UUID =
        generator.generate()
}